image: registry.gitlab.com/fdroid/ci-images-server:latest

lint:
  before_script:
    - printf "Package\x3a androguard fdroidserver python3-asn1crypto python3-ruamel.yaml yamllint\nPin\x3a release a=stretch-backports\nPin-Priority\x3a 500\n" > /etc/apt/preferences.d/debian-stretch-backports.pref
    - echo "deb http://deb.debian.org/debian/ stretch-backports main" > /etc/apt/sources.list.d/backports.list
    - apt-get update
    - apt-get -qy dist-upgrade

    - rm -rf fdroidserver
    - mkdir fdroidserver
    - git ls-remote https://gitlab.com/fdroid/fdroidserver.git master
    - curl --silent https://gitlab.com/fdroid/fdroidserver/-/archive/master/fdroidserver-master.tar.gz
        | tar -xz --directory=fdroidserver --strip-components=1
    - export PATH="$PWD/fdroidserver:$PATH"
  script:
    # if this is a merge request fork, then only check relevant apps
    - if [ "$CI_PROJECT_NAMESPACE" != "fdroid" ]; then
        git fetch https://gitlab.com/guardianproject/fdroid-metadata.git;
        test -d build || mkdir build;
        files=`git diff --name-only --diff-filter=d FETCH_HEAD...HEAD`;
        for f in $files; do
           appid=`echo $f | sed -n -e 's,^metadata/\([^/][^/]*\)\.yml,\1,p'`;
           if [ -n "$appid" ]; then
             export CHANGED="$CHANGED $appid";
             testcmd="git -C build clone `sed -En 's,^Repo\W +(https?://),\1u:p@,p' $f`";
           fi;
        done;
        set -x;
        apt-get install python3-colorama;
        ./tools/check-git-repo-availability.py $files;
        ./tools/audit-gradle.py $CHANGED;
        set +x;
      fi
    - fdroid lint -f $CHANGED || true  # too pedantic for us
    - export EXITVALUE=0
    - fdroid readmeta || export EXITVALUE=1
    - apt-get -qy update
    - apt-get -qy install --no-install-recommends exiftool yamllint
    - find metadata/ -name '*.jp*g' -o -name '*.png' | xargs exiftool -all=
    - echo "these images have EXIF that must be stripped:"
    - git --no-pager diff --stat
    - git --no-pager diff --name-only --exit-code || export EXITVALUE=1
    - ./tools/check-localized-metadata.py || export EXITVALUE=1
    - ./tools/check-keyalias-collision.py || export EXITVALUE=1
    - ./tools/check-metadata-summary-whitespace.py || export EXITVALUE=1
    - for f in metadata/*.yml; do yamllint $f || export EXITVALUE=1; done
    - exit $EXITVALUE
