#!/bin/sh -ex

test -d repo

. ../variables
basedir=`cd $(dirname $0); pwd`

for f in $basedir/build/*; do
    test -d $f/.git || continue
    echo $f
    git -C $f clean -fdx
    git -C $f checkout master
    git -C $f reset --hard
    git -C $f pull --ff-only
done

cd $basedir
chmod 0600 config.yml
~/code/fdroid/fdroidserver/fdroid update --verbose --delete-unknown --nosign

if ./index-unchanged.py; then
    echo index unchanged, do not publish
    exit
fi

~/code/fdroid/fdroidserver/fdroid signindex -v

export SSH_AUTH_SOCK=/run/user/1000/gnupg/S.gpg-agent.ssh
while ! ~/code/fdroid/fdroidserver/fdroid deploy -v; do
    sleep 5
done
